<?php
declare(strict_types=1);

/**
 * Minimal single-page PDF writer (Helvetica, no external deps).
 */
function simple_pdf_escape(string $text): string
{
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
}

/** @param array<int, string> $lines */
function simple_pdf_write(string $filepath, string $title, array $lines): void
{
    $dir = dirname($filepath);
    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
        throw new RuntimeException('Cannot create report storage directory');
    }

    $all = array_merge([$title, str_repeat('─', 60), ''], $lines, ['', 'Generated by Lapok DMS · ' . date('Y-m-d H:i')]);
    $stream = "BT /F1 12 Tf 50 780 Td (Lapok DMS) Tj ET\n";
    $y = 755;
    foreach ($all as $i => $line) {
        $size = $i === 0 ? 14 : 11;
        $esc = simple_pdf_escape(mb_substr($line, 0, 95));
        $stream .= "BT /F1 {$size} Tf 50 {$y} Td ({$esc}) Tj ET\n";
        $y -= ($i === 0 ? 22 : 14);
        if ($y < 50) {
            break;
        }
    }

    $len = strlen($stream);
    $objects = [];
    $objects[] = "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n";
    $objects[] = "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n";
    $objects[] = "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj\n";
    $objects[] = "4 0 obj << /Length {$len} >> stream\n{$stream}endstream endobj\n";
    $objects[] = "5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n";

    $pdf = "%PDF-1.4\n";
    $offsets = [0];
    foreach ($objects as $obj) {
        $offsets[] = strlen($pdf);
        $pdf .= $obj;
    }
    $xrefPos = strlen($pdf);
    $pdf .= "xref\n0 " . count($offsets) . "\n";
    $pdf .= "0000000000 65535 f \n";
    for ($i = 1; $i < count($offsets); $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    }
    $pdf .= "trailer << /Size " . count($offsets) . " /Root 1 0 R >>\nstartxref\n{$xrefPos}\n%%EOF";

    if (file_put_contents($filepath, $pdf) === false) {
        throw new RuntimeException('Failed to write PDF');
    }
}
