<?php
declare(strict_types=1);

/**
 * Lightweight PDF writer with Outpost DMS branded header (Helvetica + embedded JPEG logo).
 * Multi-page, WinAnsi-safe text (no UTF-8 garbage / &&&&), no GD required for JPEG.
 */

/**
 * Normalize report text to WinAnsi-safe ASCII so Helvetica never shows garbage like &&&& / boxes.
 */
function simple_pdf_plain(string $text): string
{
    $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $map = [
        '·' => ' - ',
        '•' => '- ',
        '–' => '-',
        '—' => '-',
        '−' => '-',
        '‘' => "'",
        '’' => "'",
        '“' => '"',
        '”' => '"',
        '…' => '...',
        '×' => 'x',
        '≤' => '<=',
        '≥' => '>=',
        '®' => '(R)',
        '©' => '(C)',
        "\xC2\xA0" => ' ',
    ];
    $text = strtr($text, $map);
    $text = preg_replace('/[^\x09\x0A\x0D\x20-\x7E]/', '', $text) ?? $text;
    $text = preg_replace('/\s+/', ' ', $text) ?? $text;
    return trim($text);
}

function simple_pdf_escape(string $text): string
{
    $text = simple_pdf_plain($text);
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
}

function simple_pdf_clip(string $text, int $max): string
{
    $text = simple_pdf_plain($text);
    if (strlen($text) <= $max) {
        return $text;
    }
    return rtrim(substr($text, 0, max(0, $max - 3))) . '...';
}

function simple_pdf_logo_path(): string
{
    $base = dirname(__DIR__) . '/assets/img';
    foreach (['outpost-dms-logo.jpg', 'outpost-dms-logo.jpeg', 'lapok-dms-logo.jpg'] as $name) {
        $path = $base . '/' . $name;
        if (is_file($path) && filesize($path) > 0) {
            return $path;
        }
    }
    return $base . '/outpost-dms-logo.jpg';
}

/**
 * @return array{bytes: string, width: int, height: int}|null
 */
function simple_pdf_load_logo(): ?array
{
    $path = simple_pdf_logo_path();
    if (!is_file($path) || !preg_match('/\.jpe?g$/i', $path)) {
        return null;
    }
    $bytes = (string) file_get_contents($path);
    if ($bytes === '' || strncmp($bytes, "\xFF\xD8", 2) !== 0) {
        return null;
    }
    $info = @getimagesize($path);
    if (!is_array($info) || (int) ($info[0] ?? 0) <= 0 || (int) ($info[1] ?? 0) <= 0) {
        return null;
    }
    $channels = (int) ($info['channels'] ?? 3);
    if ($channels !== 3 && $channels !== 0) {
        return null;
    }
    return [
        'bytes' => $bytes,
        'width' => (int) $info[0],
        'height' => (int) $info[1],
    ];
}

/**
 * @param array{
 *   company?: string,
 *   tagline?: string,
 *   doc_title?: string,
 *   meta?: array<string, string>,
 *   sections?: list<array{heading: string, lines: list<string>}>,
 *   footer?: string
 * }|null $layout
 * @param array<int, string> $lines
 */
function simple_pdf_write(string $filepath, string $title, array $lines, ?array $layout = null): void
{
    $dir = dirname($filepath);
    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
        throw new RuntimeException('Cannot create report storage directory');
    }

    if ($layout === null) {
        $layout = simple_pdf_layout_from_lines($title, $lines);
    } else {
        $layout['doc_title'] = $layout['doc_title'] ?? $title;
    }

    $company = simple_pdf_plain((string) ($layout['company'] ?? 'OUTPOST DMS'));
    $tagline = simple_pdf_plain((string) ($layout['tagline'] ?? 'Depot Management System'));
    $docTitle = simple_pdf_plain((string) ($layout['doc_title'] ?? $title));
    /** @var array<string, string> $meta */
    $meta = $layout['meta'] ?? [];
    /** @var list<array{heading: string, lines: list<string>}> $sections */
    $sections = $layout['sections'] ?? [];
    $footer = simple_pdf_plain((string) ($layout['footer'] ?? ('Generated by Outpost DMS - ' . date('Y-m-d H:i'))));

    $logo = simple_pdf_load_logo();
    $hasLogo = $logo !== null;
    $logoBytes = $hasLogo ? $logo['bytes'] : '';
    $logoW = $hasLogo ? $logo['width'] : 0;
    $logoH = $hasLogo ? $logo['height'] : 0;

    // Flatten paint ops into pages as content overflows
    $pages = [];
    $stream = '';
    $y = 0.0;
    $pageNo = 0;

    $startPage = function (bool $withTitle) use (
        &$stream,
        &$y,
        &$pageNo,
        $hasLogo,
        $logoW,
        $logoH,
        $company,
        $tagline,
        $docTitle,
        $meta
    ): void {
        $pageNo++;
        $stream = '';
        $logoDraw = 56.0;
        $headerTop = 772.0;
        $textX = 50.0;

        if ($hasLogo) {
            $drawW = $logoDraw;
            $drawH = $drawW * ($logoH / max(1, $logoW));
            $logoX = 50.0;
            $logoY = $headerTop - $drawH;
            $stream .= sprintf("q %.2F 0 0 %.2F %.2F %.2F cm /Im1 Do Q\n", $drawW, $drawH, $logoX, $logoY);
            $textX = 50.0 + $drawW + 12.0;
            $nameY = $logoY + $drawH - 18.0;
            $tagY = $nameY - 14.0;
        } else {
            $nameY = 758.0;
            $tagY = 744.0;
        }

        $stream .= "0.059 0.090 0.165 rg\n";
        $stream .= 'BT /F2 14 Tf ' . sprintf('%.1f %.1f', $textX, $nameY) . ' Td (' . simple_pdf_escape($company) . ") Tj ET\n";
        $stream .= "0.45 0.45 0.45 rg\n";
        $stream .= 'BT /F1 9 Tf ' . sprintf('%.1f %.1f', $textX, $tagY) . ' Td (' . simple_pdf_escape($tagline) . ") Tj ET\n";

        $ruleY = ($hasLogo ? ($headerTop - $logoDraw - 10.0) : 732.0);
        $stream .= "0.898 0.243 0.243 RG\n2 w\n50 {$ruleY} m 562 {$ruleY} l S\n1 w\n";
        $y = $ruleY - 22.0;

        if ($withTitle) {
            $stream .= "0 0 0 rg\n";
            $stream .= 'BT /F2 16 Tf 50 ' . sprintf('%.1f', $y) . ' Td (' . simple_pdf_escape(simple_pdf_clip($docTitle, 70)) . ") Tj ET\n";
            $y -= 18;
            $stream .= "0.85 0.85 0.85 RG\n50 {$y} m 562 {$y} l S\n";
            $y -= 16;

            if ($meta) {
                $stream .= "0 0 0 rg\n";
                foreach ($meta as $label => $value) {
                    if ($y < 90) {
                        break;
                    }
                    $lab = simple_pdf_plain(rtrim((string) $label)) . ': ';
                    $val = simple_pdf_plain((string) $value);
                    $stream .= 'BT /F2 10 Tf 50 ' . sprintf('%.1f', $y) . ' Td (' . simple_pdf_escape(simple_pdf_clip($lab, 40)) . ") Tj ET\n";
                    $labW = strlen($lab) * 5.4;
                    $stream .= 'BT /F1 10 Tf ' . sprintf('%.1f %.1f', 50 + $labW, $y) . ' Td (' . simple_pdf_escape(simple_pdf_clip($val, 70)) . ") Tj ET\n";
                    $y -= 13;
                }
                $y -= 6;
                $stream .= "0.85 0.85 0.85 RG\n50 {$y} m 562 {$y} l S\n";
                $y -= 16;
            }
        } else {
            $stream .= "0.35 0.35 0.35 rg\n";
            $stream .= 'BT /F1 9 Tf 50 ' . sprintf('%.1f', $y) . ' Td (' . simple_pdf_escape(simple_pdf_clip($docTitle . ' (continued)', 80)) . ") Tj ET\n";
            $y -= 16;
        }
    };

    $finishPage = function () use (&$pages, &$stream, $footer, &$pageNo): void {
        $stream .= "0.85 0.85 0.85 RG\n50 42 m 562 42 l S\n";
        $foot = simple_pdf_clip($footer . '  |  Page ' . $pageNo, 95);
        $stream .= "0.45 0.45 0.45 rg\nBT /F1 8 Tf 50 30 Td (" . simple_pdf_escape($foot) . ") Tj ET\n";
        $pages[] = $stream;
        $stream = '';
    };

    $ensureSpace = function (float $need) use (&$y, $startPage, $finishPage): void {
        if ($y < $need) {
            $finishPage();
            $startPage(false);
        }
    };

    $startPage(true);

    foreach ($sections as $section) {
        $heading = simple_pdf_plain((string) ($section['heading'] ?? ''));
        $bodyLines = $section['lines'] ?? [];
        $ensureSpace(80);
        if ($heading !== '') {
            $stream .= "0.898 0.243 0.243 rg\n";
            $stream .= 'BT /F2 12 Tf 50 ' . sprintf('%.1f', $y) . ' Td (' . simple_pdf_escape(strtoupper(simple_pdf_clip($heading, 60))) . ") Tj ET\n";
            $y -= 16;
            // Underline the section title lightly
            $stream .= "0.898 0.243 0.243 RG\n1 w\n50 {$y} m 320 {$y} l S\n";
            $y -= 12;
            $stream .= "0 0 0 rg\n";
        }
        foreach ($bodyLines as $line) {
            $rawLine = (string) $line;
            $indentLevel = 0;
            if (preg_match('/^(\s+)/', $rawLine, $im)) {
                $indentLevel = strlen($im[1]) >= 4 ? 2 : 1;
            }
            $text = simple_pdf_plain($rawLine);
            if ($text === '') {
                $y -= 6;
                continue;
            }
            // Subheading lines end with ":" and have no value — bold, no bullet
            $isSubhead = str_ends_with($text, ':') && !str_contains(rtrim($text, ':'), ':');
            // Numbered steps keep their number; everything else gets a bullet
            $isNumbered = (bool) preg_match('/^\d+\.\s/', $text);
            $x = 54.0 + ($indentLevel * 14.0);

            if ($isSubhead) {
                $ensureSpace(60);
                $stream .= 'BT /F2 10 Tf ' . sprintf('%.1f %.1f', $x, $y) . ' Td (' . simple_pdf_escape(simple_pdf_clip($text, 88)) . ") Tj ET\n";
                $y -= 13;
                continue;
            }

            $label = '';
            $value = $text;
            if (preg_match('/^([^:]{1,55}):\s*(.+)$/', $text, $m)) {
                $label = $m[1];
                $value = $m[2];
            }

            $bullet = $isNumbered ? '' : '- ';
            $prefix = $bullet;
            if ($label !== '') {
                // Draw bullet + bold label, then regular value on same baseline
                $ensureSpace(60);
                $labelBit = $prefix . $label . ': ';
                $stream .= 'BT /F2 10 Tf ' . sprintf('%.1f %.1f', $x, $y) . ' Td (' . simple_pdf_escape($labelBit) . ") Tj ET\n";
                // Approximate label width (Helvetica-Bold ~0.55em at 10pt)
                $labelWidth = strlen($labelBit) * 5.4;
                $valueChunks = simple_pdf_wrap($value, max(20, (int) ((520 - $x - $labelWidth) / 5.2)));
                $first = array_shift($valueChunks);
                $stream .= 'BT /F1 10 Tf ' . sprintf('%.1f %.1f', $x + $labelWidth, $y) . ' Td (' . simple_pdf_escape((string) $first) . ") Tj ET\n";
                $y -= 12;
                foreach ($valueChunks as $chunk) {
                    $ensureSpace(60);
                    $stream .= 'BT /F1 10 Tf ' . sprintf('%.1f %.1f', $x + 12, $y) . ' Td (' . simple_pdf_escape($chunk) . ") Tj ET\n";
                    $y -= 12;
                }
                continue;
            }

            // Plain bulleted / numbered line (bold first word or status keyword)
            $display = $prefix . $text;
            if (preg_match('/^(PENDING|CONFIRMED|OK|CASH CONFIRMATION)\b(.*)$/i', $text, $sm)) {
                $ensureSpace(60);
                $kw = strtoupper($sm[1]);
                $rest = $sm[2];
                $stream .= 'BT /F2 10 Tf ' . sprintf('%.1f %.1f', $x, $y) . ' Td (' . simple_pdf_escape($prefix . $kw) . ") Tj ET\n";
                $kwWidth = strlen($prefix . $kw) * 5.4;
                if (trim($rest) !== '') {
                    $stream .= 'BT /F1 10 Tf ' . sprintf('%.1f %.1f', $x + $kwWidth, $y) . ' Td (' . simple_pdf_escape($rest) . ") Tj ET\n";
                }
                $y -= 12;
                continue;
            }

            $chunks = simple_pdf_wrap($display, max(20, (int) ((520 - $x) / 5.2)));
            $firstChunk = true;
            foreach ($chunks as $chunk) {
                $ensureSpace(60);
                // First chunk of a key line: lightly bold if it is a short standalone title-like line
                $font = ($firstChunk && !$isNumbered && strlen($text) <= 40 && !str_contains($text, '|')) ? '/F2' : '/F1';
                $stream .= 'BT ' . $font . ' 10 Tf ' . sprintf('%.1f %.1f', $firstChunk ? $x : $x + 10, $y) . ' Td (' . simple_pdf_escape($chunk) . ") Tj ET\n";
                $y -= 12;
                $firstChunk = false;
            }
        }
        $y -= 12;
    }

    $finishPage();

    // Build PDF objects
    $objects = [];
    $objects[] = ''; // placeholder catalog later
    $objects[] = ''; // placeholder pages later

    $fontF1 = count($objects) + 1;
    $objects[] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
    $fontF2 = count($objects) + 1;
    $objects[] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";

    $imgObj = 0;
    if ($hasLogo) {
        $imgObj = count($objects) + 1;
        $imgLen = strlen($logoBytes);
        $objects[] = "<< /Type /XObject /Subtype /Image /Width {$logoW} /Height {$logoH} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length {$imgLen} >>\nstream\n"
            . $logoBytes
            . "\nendstream";
    }

    $xObj = $hasLogo ? " /XObject << /Im1 {$imgObj} 0 R >>" : '';
    $resources = "<< /Font << /F1 {$fontF1} 0 R /F2 {$fontF2} 0 R >>{$xObj} >>";

    $pageObjNums = [];
    $contentObjNums = [];
    foreach ($pages as $pageStream) {
        $contentObjNums[] = count($objects) + 1;
        $len = strlen($pageStream);
        $objects[] = "<< /Length {$len} >>\nstream\n{$pageStream}endstream";
        $pageObjNums[] = count($objects) + 1;
        $objects[] = 'PAGE_PLACEHOLDER';
    }

    // Fill page objects now that content ids are known
    foreach ($pageObjNums as $i => $pageNum) {
        $contentNum = $contentObjNums[$i];
        $objects[$pageNum - 1] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents {$contentNum} 0 R /Resources {$resources} >>";
    }

    $kids = implode(' ', array_map(static fn($n) => $n . ' 0 R', $pageObjNums));
    $objects[0] = '<< /Type /Catalog /Pages 2 0 R >>';
    $objects[1] = '<< /Type /Pages /Kids [' . $kids . '] /Count ' . count($pageObjNums) . ' >>';

    $pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
    $offsets = [0];
    foreach ($objects as $idx => $body) {
        $offsets[] = strlen($pdf);
        $pdf .= ($idx + 1) . " 0 obj\n" . $body . "\nendobj\n";
    }
    $xrefPos = strlen($pdf);
    $pdf .= 'xref' . "\n0 " . count($offsets) . "\n";
    $pdf .= "0000000000 65535 f \n";
    for ($i = 1; $i < count($offsets); $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    }
    $pdf .= 'trailer << /Size ' . count($offsets) . " /Root 1 0 R >>\nstartxref\n{$xrefPos}\n%%EOF\n";

    if (file_put_contents($filepath, $pdf) === false) {
        throw new RuntimeException('Failed to write PDF');
    }
}

/**
 * @param array<int, string> $lines
 * @return array{company: string, tagline: string, doc_title: string, meta: array<string, string>, sections: list<array{heading: string, lines: list<string>}>, footer: string}
 */
function simple_pdf_layout_from_lines(string $title, array $lines): array
{
    return [
        'company' => 'OUTPOST DMS',
        'tagline' => 'Depot Management System',
        'doc_title' => $title,
        'meta' => [],
        'sections' => [
            ['heading' => 'Report details', 'lines' => array_values($lines)],
        ],
        'footer' => 'Generated by Outpost DMS - ' . date('Y-m-d H:i'),
    ];
}

/** @return list<string> */
function simple_pdf_wrap(string $text, int $width): array
{
    $text = simple_pdf_plain($text);
    if ($text === '') {
        return [''];
    }
    if (strlen($text) <= $width) {
        return [$text];
    }
    $words = explode(' ', $text);
    $lines = [];
    $cur = '';
    foreach ($words as $w) {
        $try = $cur === '' ? $w : $cur . ' ' . $w;
        if (strlen($try) <= $width) {
            $cur = $try;
        } else {
            if ($cur !== '') {
                $lines[] = $cur;
            }
            // Hard-break very long tokens
            while (strlen($w) > $width) {
                $lines[] = substr($w, 0, $width);
                $w = substr($w, $width);
            }
            $cur = $w;
        }
    }
    if ($cur !== '') {
        $lines[] = $cur;
    }
    return $lines ?: [$text];
}

function simple_pdf_ugx(float $n): string
{
    $sign = $n < 0 ? '-' : '';
    return $sign . 'UGX ' . number_format(abs($n), 0);
}
